[Metadata]
Title = "KompetenzwerkD Project Metadata Schema"
Changed = "21.04.2020"
Version = "0.3"
Location = "https://raw.githubusercontent.com/KompetenzwerkD/fdm-schemas/master/schemas/project_metadata_schema.toml"

#Namespaces = schema.org

#overview=
#
#general=
#- Name
#- Identifier
#- Url
#- StartDate
#- EndDate
#- FundingAgency*
#- Description
#
#organization
#- ParentOrganization
#- MemberOf
#- ProjectLeader**
#- Employee
#
#contact information
#- Address
#- Email

#* proposed, not yet fully implemented in schema.org
#** not in schema.org

# Todos/open-questions=
# - Identifier -> what can/should be used as an identifier?
# - Organizations -> how to standardize organization input?
# - employees/project leader -> identifier? orcid?


[General]

    [General.Name]
    Label = "Name"
    URI = "https://schema.org/name"
    Definition = "The name of the project."
    Comment = ""
    Type = "property"
    Obligation = "mandatory"
    Occurrence = "1/1"
    Datatype = "Text" 
    Language = ""

    [General.dentifier]
    Label = "Identifier"
    URI = "https://schema.org/identifier"
    Definition = "The identifier property represents any kind of identifier for this project."
    Comment = ""
    Type = "property"
    Obligation = "mandatory"
    Occurrence = "1/1"
    Datatype = "URI, Text"
    Language = ""

    [General.Url]
    Label = "Url"
    URI = "https://schema.org/url"
    Definition = "URL of this project."
    Comment = ""
    Type = "property"
    Obligation = "recommended"
    Occurrence = "0/1"
    Datatype = "Url"
    Language = ""

    [General.StartDate]
    Label = "Start Date"
    URI = "https://schema.org/startDate"
    Definition = "The start date and time of this project (in ISO 8601 date format)."
    Comment = ""
    Type = "property"
    Obligation = "mandatory"
    Occurrence = "1/1"
    Datatype = "Date (ISO_8601)"
    Language = ""

    [General.EndDate]
    Label = "End Date"
    URI = "https://schema.org/endDate"
    Definition = "The end date and time of this project (in ISO 8601 date format)."
    Comment = ""
    Type = "property"
    Obligation = "recommended"
    Occurrence = "0/1"
    Datatype = "Date (ISO_8601)"
    Language = "eng"

    [General.Description]
    Label = "Description"
    URI = "https://schema.org/description"
    Definition = "A description of the project in English."
    Comment = ""
    Type = "property"
    Obligation = "mandatory"
    Occurrence = "1/1"
    Datatype = "Text"
    Language = "eng"

    [General.Beschreibung]
    Label = "Beschreibung"
    URI = "https://schema.org/description"
    Definition = "A description of the project in German."
    Comment = ""
    Type = "property"
    Obligation = "mandatory"
    Occurrence = "1/1"
    Datatype = "Text"
    Language = "deu"


[Organization]

    [Organization.ParentOrganization]
    Label = "Parent Organization"
    URI = "https://schema.org/parentOrganization"
    Definition = "The organization (ID) responsible for this project."
    Comment = ""
    Type = "property"
    Obligation = "mendatory"
    Occurrence = "1/n"
    Datatype = "ID"
    Language = "eng"
    Qualifier = [ "IdentifierType", "Label" ]
    Hint = """
    # Recomnended Identifier:
    # VIAF - http://viaf.org/
    """

    [Organization.MemberOf]
    Label = "Member Of"
    URI = "https://schema.org/memberOf"
    Definition = "An Organization (ID) to which this project is affiliated." 
    Comment = ""
    Type = "property"
    Obligation = "optional"
    Occurrence = "0/n"
    Datatype = "ID"
    Language = "eng"
    Qualifier = [ "IdentifierType", "Label" ]
    Hint = """
    # Recomnended Identifier:
    # VIAF - http://viaf.org/
    """

    [Organization.FundingAgency]
    Label = "Funding Agency"
    URI = "???"
    Definition = "Organization (ID) providing project funding."
    Comment = ""
    Type = "property"
    Obligation = "recommended"
    Occurrence = "0/1"
    Datatype = "ID"
    Language = "eng"
    Qualifier = [ "IdentifierType", "Label" ]
    Hint = """
    # Recomnended Identifier:
    # VIAF - http://viaf.org/
    """

    [Organization.ProjectLeader]
    Label = "Project Leader"
    URI = "???"
    Definition = "Person (ID) in charge of this project."
    Comment = ""
    Type = "property"
    Obligation = "mendatory"
    Occurrence = "1/n"
    Datatype = "ID"
    Language = "eng"
    Qualifier = [ "IdentifierType", "Label" ]
    Hint = """
    # Recomnended Identifiers:
    # ORCID - https://orcid.org/Alternatives
    # GND - https://www.dnb.de/DE/Professionell/Standardisierung/GND/gnd_node.html
    """
    

    [Organization.Employee]
    Label = "Employee"
    URI = "https://schema.org/employee"
    Definition = "Person (ID) working in this project."
    Comment = ""
    Type = "property"
    Obligation = "recommended"
    Occurrence = "0/n"
    Datatype = "ID"
    Language = "eng"
    Qualifier = [ "IdentifierType","Label" ]
    Hint = """
    # Recommended Identifiers:
    # ORCID - https://orcid.org/Alternatives
    # GND - https://www.dnb.de/DE/Professionell/Standardisierung/GND/gnd_node.html
    """

[Contact]

    [Contact.Email]
    Label = "Email"
    URI = "https://schema.org/email"
    Definition = "Email address."
    Comment = ""
    Type = "property"
    Obligation = "mandatory"
    Occurrence = "1/n"
    Datatype = "Text"
    Language = "eng"

    [Contact.Address]
    Label = "Address"
    URI = "https://schema.org/address"
    Definition = "Physical address."
    Comment = ""
    Type = "property"
    Obligation = "mandatory"
    Occurrence = "1/n"
    Datatype= "Text"
    Language = "eng"
